import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime
from config import GMAIL_USER, GMAIL_APP_PASSWORD

def _build_html(subject: str, sender_name: str, summaries: list[dict]) -> str:
    """Compose the HTML content for the summary email"""
    now = datetime.now().strftime("%Y/%m/%d %H:%M")

    articles_html = ""
    for i, item in enumerate(summaries, 1):
        title = item.get('title', 'No Title')
        description = item.get('description', '')
        summary_html = item['summary'].replace('\n', '<br>')
        
        # Handle Markdown bold
        import re
        summary_html = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', summary_html)

        articles_html += f"""
        <div style="margin-bottom:32px; padding:20px; background:#ffffff;
                    border-radius:8px; border:1px solid #e0e0e0; border-left: 6px solid #1a73e8;">
            <div style="font-size:13px; color:#888; margin-bottom:6px;">Article {i}</div>
            <div style="font-size:18px; font-weight:bold; color:#2c3e50; margin-bottom:4px;">
                {title}
            </div>
            <div style="font-size:14px; color:#7f8c8d; font-style:italic; margin-bottom:12px;">
                {description}
            </div>
            <div style="margin-bottom:12px;">
                <a href="{item['url']}" style="color:#1a73e8; word-break:break-all;
                   font-size:13px;">{item['url']}</a>
            </div>
            <div style="font-size:15px; line-height:1.8; color:#333; background:#f9f9f9; padding:15px; border-radius:5px;">
                {summary_html}
            </div>
        </div>
        """

    return f"""
    <!DOCTYPE html>
    <html>
    <head><meta charset="utf-8"></head>
    <body style="font-family: 'Helvetica Neue', Arial, sans-serif;
                 background:#f5f5f5; margin:0; padding:24px;">
        <div style="max-width:720px; margin:0 auto;">

            <!-- Header -->
            <div style="background:#1a73e8; color:white; padding:24px;
                        border-radius:8px 8px 0 0; margin-bottom:4px;">
                <div style="font-size:12px; opacity:0.8; margin-bottom:4px;">
                    Newsletter Summary · {now}
                </div>
                <div style="font-size:22px; font-weight:bold;">
                    📰 {subject}
                </div>
                <div style="font-size:13px; opacity:0.8; margin-top:6px;">
                    Source: {sender_name} · Total {len(summaries)} articles
                </div>
            </div>

            <!-- Articles -->
            <div style="background:#f9f9f9; padding:20px;
                        border-radius:0 0 8px 8px; border:1px solid #e0e0e0;">
                {articles_html}
            </div>

            <!-- Footer -->
            <div style="text-align:center; font-size:12px; color:#aaa; margin-top:16px;">
                This summary was automatically generated by Newsletter Bot
            </div>
        </div>
    </body>
    </html>
    """


def send_summary_email(subject: str, sender_name: str, summaries: list[dict]) -> None:
    """
    Send the summary results to self in HTML format.

    :param subject:     Original email subject
    :param sender_name: Newsletter sender name (for display)
    :param summaries:   [{'url': '...', 'summary': '...'}, ...]
    """
    if not summaries:
        print("⚠️  No summary content to send, skipping email")
        return

    msg = MIMEMultipart('alternative')
    msg['Subject'] = f"📰 [Summary] {subject}"
    msg['From']    = GMAIL_USER
    msg['To']      = GMAIL_USER

    html_content = _build_html(subject, sender_name, summaries)
    msg.attach(MIMEText(html_content, 'html', 'utf-8'))

    with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
        server.login(GMAIL_USER, GMAIL_APP_PASSWORD)
        server.sendmail(GMAIL_USER, GMAIL_USER, msg.as_string())

    print(f"✉️  Summary email sent: {subject} ({len(summaries)} articles)")
